version: '2.4'
services:
  seed_node:
    image: "strapdata.azurecr.io/strapdata/elassandra-dev:latest"
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_CGROUP_MEMORY_LIMIT=true"
      - "DEBUG=true"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m
    ports:
      - "9042:9042"
      - "9200:9200"
  node:
    image: "strapdata.azurecr.io/strapdata/elassandra-dev:latest"
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_CGROUP_MEMORY_LIMIT=true"
      - "CASSANDRA_SEEDS=seed_node"
      - "DEBUG=true"
    links:
      - seed_node
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.8.4
    environment:
      - "ELASTICSEARCH_URL=http://seed_node:9200"
    ports:
      - "5601:5601"
    mem_limit: 500m